# citadel — top-level NixOS configuration.
#
# This file deliberately contains almost nothing: it wires together the
# machine-specific hardware config (generated at install time, not in git)
# and a set of small, single-purpose modules. When you wonder "where is X
# configured?", the module names below are the map.
{ config, pkgs, ... }:

{
  imports = [
    # Generated by `nixos-generate-config` during install; lives only on the
    # machine (gitignored). See hardware-configuration.nix.example.
    ./hardware-configuration.nix

    ./modules/base.nix           # locale, timezone, users, nix GC
    ./modules/ssh.nix            # key-only SSH
    ./modules/tailscale.nix
    ./modules/virtualization.nix # libvirt/KVM, swtpm, OVMF
    ./modules/monitoring.nix     # smartd, chrony, sensors, fwupd
    ./modules/firewall.nix
    ./modules/alerts.nix         # Slack alert timers

    # Opt-in: only if this box must use WiFi instead of Ethernet (wire it if
    # you can — see the header of wifi.nix for why, and for the secrets file
    # you must create on the machine first).
    # ./modules/wifi.nix
  ];

  # Change the hostname here (and nowhere else). Keep it short — it shows up
  # in your Tailscale device list and shell prompts.
  networking.hostName = "citadel";

  # UEFI boot via systemd-boot: the simple, modern choice. No GRUB, no MBR.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # DHCP on whatever NIC the hardware config detects. This machine sits on a
  # LAN; give it a static lease in the router if you want a stable IP
  # (Tailscale gives it a stable name regardless).
  networking.useDHCP = true;

  # ── DO NOT CHANGE AFTER INSTALL ──────────────────────────────────────────
  # stateVersion pins the defaults for stateful data formats (databases,
  # config file layouts) to the release that first created them. It is NOT
  # "the version I'm running" — you upgrade NixOS by moving the channel, and
  # this stays at the release you originally installed. Changing it later can
  # silently migrate on-disk state. Set once, forget forever.
  system.stateVersion = "26.05";
}
