#!/usr/bin/env bash
# Post-install bootstrap: point /etc/nixos at this repo's config and rebuild.
# Run ON THE HOST, from a clone of this repo, after `nixos-install` +
# first boot (docs/install.md) — and again any time you've pulled config
# changes and want to apply them.
#
#   git clone <repo> && cd citadel && ./scripts/bootstrap.sh
#
# Copy, not symlink: /etc/nixos stays self-contained and the repo can live
# anywhere. The machine's generated hardware-configuration.nix is preserved.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [ ! -f /etc/nixos/hardware-configuration.nix ]; then
  echo "error: /etc/nixos/hardware-configuration.nix is missing." >&2
  echo "It is generated by nixos-generate-config during install and must" >&2
  echo "stay on the machine (it's intentionally not in the repo)." >&2
  exit 1
fi

if grep -rq CHANGEME "$REPO_DIR/nixos"; then
  echo "error: unfilled CHANGEME placeholders in nixos/ — fix these first:" >&2
  grep -rn CHANGEME "$REPO_DIR/nixos" >&2
  exit 1
fi

echo "Syncing $REPO_DIR/nixos/ -> /etc/nixos/"
# Remove old modules so renamed/deleted files don't linger, then copy fresh.
sudo rm -rf /etc/nixos/modules
sudo cp -r "$REPO_DIR/nixos/modules" /etc/nixos/modules
sudo cp "$REPO_DIR/nixos/configuration.nix" /etc/nixos/configuration.nix

# test = build + activate WITHOUT touching the boot menu. If this bricks
# networking, a power cycle boots the previous generation. Only after test
# succeeds do we make it permanent. See docs/operations.md.
echo
echo "Running nixos-rebuild test (activates but does NOT set boot default)..."
sudo nixos-rebuild test

echo
read -r -p "test succeeded and the machine still feels right — make it permanent with switch? [y/N] " ans
if [ "${ans,,}" = "y" ]; then
  sudo nixos-rebuild switch
  echo "Switched. This config is now the boot default."
else
  echo "Left as test-only. A reboot returns to the previous generation."
fi
